from functools import reduce


def letter_to_word(password: str) -> str:
    """ a list with the letters, which turns into the letters """
    switcher: dict = {
        'a': 'apple',
        'b': 'bestbuy',
        'c': 'coffee',
        'd': 'drip',
        'e': 'egg',
        'f': 'fruit',
        'g': 'golf',
        'h': 'hulu',
        'i': 'iphone',
        'j': 'jack',
        'k': 'korean',
        'l': 'laptop',
        'm': 'music',
        'n': 'nut',
        'o': 'omelet',
        'p': 'park',
        'q': 'queen',
        'r': 'rope',
        's': 'skype',
        't': 'tokyo',
        'u': 'usa',
        'v': 'visa',
        'w': 'walmart',
        'x': 'xbox',
        'y': 'yelp',
        'z': 'zip',

        'A': 'APPLE',
        'B': 'BESTBUY',
        'C': 'COFFEE',
        'D': 'DRIP',
        'E': 'EGG',
        'F': 'FRUIT',
        'G': 'GOLF',
        'H': 'HULU',
        'I': 'IPHONE',
        'J': 'JACK',
        'K': 'KOREAN',
        'L': 'LAPTOP',
        'M': 'MUSIC',
        'N': 'NUT',
        'O': 'OMELET',
        'P': 'PARK',
        'Q': 'QUEEN',
        'R': 'ROPE',
        'S': 'SKYPE',
        'T': 'TOKYO',
        'U': 'USA',
        'V': 'VISA',
        'W': 'WALMART',
        'X': 'XBOX',
        'Y': 'YELP',
        'Z': 'ZIP',

        '0': '0',
        '1': '1',
        '2': '2',
        '3': '3',
        '4': '4',
        '5': '5',
        '6': '6',
        '7': '7',
        '8': '8',
        '9': '9',

        '-': '-',
        '~': '~',
        '#': '#',
        '&': '&',
        '@': '@',
        '{': '{',
        '}': '}',
        '+': '+',
        ')': ')',
        ':': ':',
        '!': '!',
        '=': '=',
        '*': '*',
        '_': '_',
        '%': '%',
        '<': '<',
        '>': '>',
        '$': '$',
        '|': '|',
        '[': '[',
        ']': ']',
        '^': '^',
        '?': '?',
        ' ': ' ',
    }

    res = ' '.join([switcher[password[i]] for i in range(len(password))])

    return res.strip()


if __name__ == '__main__':
    print('u can run this file as main')
